CREATE TABLE IF NOT EXISTS c_wallet (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL UNIQUE,
  BALANCE DECIMAL(15,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS c_transactions (
                                              ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                                              USER_ID BIGINT NOT NULL,
                                              AMOUNT DECIMAL(15,2) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL, -- For TCC: PENDING, CONFIRMED, CANCELED
    XID VARCHAR(128), -- For TCC fence
    BRANCH_ID BIGINT -- For TCC fence
    );

-- TCC Fence Table (required for Seata TCC mode)
CREATE TABLE IF NOT EXISTS tcc_fence_log (
                                             XID VARCHAR(128) NOT NULL,
    BRANCH_ID BIGINT NOT NULL,
    ACTION_NAME VARCHAR(64) NOT NULL,
    STATUS TINYINT NOT NULL COMMENT '0:try, 1:commit, 2:rollback',
    GMT_CREATE DATETIME NOT NULL,
    GMT_MODIFIED DATETIME NOT NULL,
    PRIMARY KEY (XID, BRANCH_ID)
    );